### ISSUE TITLE
Problème avec lever du soleil 

### ISSUE THREAD

**Issue by Francky62** [PhilippeJ-code/terrarium#2]
Bonjour, cela fait 2 jours que le lever du soleil est erroné sur tous mes terrariums, il s'éteigne vers 19h30 mais s'allume a minuit 

Hier 0 0 *** et aujourd'hui, 2 0 ***

**Comment by PhilippeJ-code** [comment]
Bonjour, chez moi ça fonctionne. Peux-tu me montrer les infos que tu as dans la configuration du plugin sous l'onglet 'Horaire'

**Comment by Francky62** [comment]
Bonjour 
Ma position, j'ai vérifié, toujours ok 
Après j'ai rien modifié par rapport aux autres jours.

Bizarre car le coucher du soleil est bon
![capture](https://user-images.githubusercontent.com/83576839/136426145-261506c2-8e44-4165-8bf0-50b0ab0dc2da.png)

**Comment by PhilippeJ-code** [comment]
Bonjour,

Vu l'erreur, je lance une correction sur le market

Philippe

**Comment by Francky62** [comment]
Bonjour

Merci pour la réactivité ;)
